<template lang="pug">
div
    h1 About page
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce varius vulputate purus. Donec porta justo non auctor volutpat. Praesent gravida facilisis odio quis finibus. Fusce molestie interdum sem quis iaculis. Integer lacinia mi faucibus, maximus est non, pharetra diam. Etiam nec massa non est tristique placerat. Vestibulum in neque et enim commodo pellentesque.
</template>

<script>
    export default {
        name: 'about-page',
    };
</script>

<style lang="scss" scoped></style>
